version: "3.7"

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
      target: dev
    container_name: backend
    environment:
      PORT: 80
    env_file:
      - .env
    links:
      - db
    ports:
      - 80:80
    tty: true
    volumes:
      - ./backend:/go/src/github.com/ryoSSS/2021_DeNA_hackathon/backend
    working_dir: /go/src/github.com/ryoSSS/2021_DeNA_hackathon/backend

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/volumes:/var/lib/mysql
    command: mysqld

  db_migrate:
    image: migrate/migrate
    container_name: db_migrate
    links:
      - db
    volumes:
      - ./db/migrations:/migrations
    entrypoint:
      sh -c "
        if ls /migrations/*.sql > /dev/null 2>&1; then

          until migrate -path /migrations -database 'mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_DATABASE}' up; do

            echo 'waiting for mysql to be connectable...'

            sleep 5

          done

        fi;
      "
