version: "3.7"

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
      target: dev
    container_name: backend
    env_file:
      - .env
    links:
      - db
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./backend:/go/src/github.com/ryoSSS/2021_DeNA_hackathon/backend
    working_dir: /go/src/github.com/ryoSSS/2021_DeNA_hackathon/backend

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/volumes:/var/lib/mysql
    command: mysqld
