version: "3.7"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: happily_nginx
    ports:
      - 80:80
    env_file:
      - .env
    extra_hosts:
      - "localhost:$HOST_IP"

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
      target: dev
    container_name: happily_backend
    environment:
      PORT: 8080
    env_file:
      - .env
    links:
      - db
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./backend:/go/src/github.com/ryoSSS/2021_DeNA_hackathon/backend
    working_dir: /go/src/github.com/ryoSSS/2021_DeNA_hackathon/backend

  db:
    image: mysql:5.7
    container_name: happily_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/volumes:/var/lib/mysql
    command: mysqld

  db_migrate:
    image: migrate/migrate
    container_name: happily_db_migrate
    links:
      - db
    volumes:
      - ./db/migrations:/migrations
    entrypoint:
      sh -c "
        if ls /migrations/*.sql > /dev/null 2>&1; then

          until migrate -path /migrations -database 'mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_DATABASE}' up; do

            echo 'waiting for mysql to be connectable...'

            sleep 5

          done

        fi;
      "
