import Head from "next/head";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<div className="text-center text-red-500">
					<h1 className="text-center">Hello World!</h1>
				</div>
			</main>
		</div>
	);
}
